[package]
name = "client"
version = "0.4.1"
edition = "2021"

[dependencies]
arc-swap = "1.6.0"
eyre = "0.6.8"
serde = { version = "1.0.143", features = ["derive"] }
hex = "0.4.3"
ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "d09f55b4f8554491e3431e01af1c32347a8781cd" }
ethers-core = { version = "2.0.8", default-features = false }
futures = "0.3.23"
log = "0.4.17"
thiserror = "1.0.37"

common = { path = "../common" }
consensus = { path = "../consensus" }
execution = { path = "../execution" }
config = { path = "../config" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonrpsee = { version = "0.15.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
ic-cdk-timers = "0.4.0"
ic-cdk = "0.10.0"
